import { QuizConfig } from '@/types/quiz';

export const styleQuiz: QuizConfig = {
  id: 'style-quiz',
  slug: 'style-quiz',
  hook: 'Your closet should feel discovered, not bought.',
  hookSubtext: 'Answer a few quick questions and uncover the kinds of rare pieces your eye naturally finds.',
  ctaLabel: 'Start the hunt →',
  questions: [
    {
      id: 'tq-q1',
      text: 'What kind of find makes you text your friends immediately?',
      subtext: 'Go with your gut — no wrong answers.',
      options: [
        { id: 'tq-q1-a', label: 'Rare designer piece', emoji: '🪙', weights: { designer_score_seeker: 3, archive_hunter: 1 } },
        { id: 'tq-q1-b', label: 'Perfect oversized jacket', emoji: '🧥', weights: { quiet_luxury_collector: 2, archive_hunter: 2 } },
        { id: 'tq-q1-c', label: 'Strange vintage item nobody else has', emoji: '🗝️', weights: { eclectic_archivist: 3, archive_hunter: 2 } },
        { id: 'tq-q1-d', label: 'Quiet luxury steal', emoji: '🤍', weights: { quiet_luxury_collector: 3, hidden_gem_collector: 1 } },
        { id: 'tq-q1-e', label: 'Beautiful worn-in basics', emoji: '✦', weights: { soft_vintage_curator: 3, hidden_gem_collector: 1 } },
        { id: 'tq-q1-f', label: 'Archive fashion piece', emoji: '📦', weights: { archive_hunter: 3, eclectic_archivist: 1 } },
        { id: 'tq-q1-g', label: 'Weird statement item', emoji: '⚡', weights: { street_romantic: 3, eclectic_archivist: 2 } },
        { id: 'tq-q1-h', label: 'Timeless coat or bag', emoji: '🧣', weights: { downtown_treasure_hunter: 3, quiet_luxury_collector: 1 } },
      ],
    },
    {
      id: 'tq-q2',
      text: 'What matters most when a piece catches your eye?',
      options: [
        { id: 'tq-q2-a', label: 'Texture', emoji: '🪡', weights: { soft_vintage_curator: 3, quiet_luxury_collector: 1 } },
        { id: 'tq-q2-b', label: 'Silhouette', emoji: '🖤', weights: { archive_hunter: 3, quiet_luxury_collector: 2 } },
        { id: 'tq-q2-c', label: 'Story / history', emoji: '📖', weights: { downtown_treasure_hunter: 3, soft_vintage_curator: 2 } },
        { id: 'tq-q2-d', label: 'Rarity', emoji: '💎', weights: { hidden_gem_collector: 3, designer_score_seeker: 2 } },
        { id: 'tq-q2-e', label: 'Brand or label', emoji: '🏷️', weights: { designer_score_seeker: 3 } },
        { id: 'tq-q2-f', label: 'Fabric quality', emoji: '✨', weights: { quiet_luxury_collector: 3, archive_hunter: 1 } },
        { id: 'tq-q2-g', label: 'Emotional vibe', emoji: '🌙', weights: { street_romantic: 3, soft_vintage_curator: 2 } },
      ],
    },
    {
      id: 'tq-q3',
      text: 'What kind of wardrobe feels most impressive to you?',
      options: [
        { id: 'tq-q3-a', label: 'Looks expensive without trying', emoji: '🧥', weights: { quiet_luxury_collector: 3, hidden_gem_collector: 1 } },
        { id: 'tq-q3-b', label: 'Feels deeply personal', emoji: '🪞', weights: { soft_vintage_curator: 3, street_romantic: 1 } },
        { id: 'tq-q3-c', label: 'Full of hidden gems', emoji: '💎', weights: { hidden_gem_collector: 3, downtown_treasure_hunter: 2 } },
        { id: 'tq-q3-d', label: 'Vintage and layered', emoji: '📦', weights: { archive_hunter: 3, eclectic_archivist: 2 } },
        { id: 'tq-q3-e', label: 'Hard to categorize', emoji: '⚡', weights: { eclectic_archivist: 3, street_romantic: 2 } },
        { id: 'tq-q3-f', label: 'Understated but unforgettable', emoji: '🤍', weights: { quiet_luxury_collector: 2, archive_hunter: 2 } },
        { id: 'tq-q3-g', label: 'Collected over years', emoji: '🗝️', weights: { downtown_treasure_hunter: 3, soft_vintage_curator: 2 } },
      ],
    },
    {
      id: 'tq-q4',
      text: 'What instantly ruins a piece for you?',
      options: [
        { id: 'tq-q4-a', label: 'Loud branding', emoji: '🚫', weights: { quiet_luxury_collector: 3, archive_hunter: 2 } },
        { id: 'tq-q4-b', label: 'Fast-fashion energy', emoji: '⚡', weights: { archive_hunter: 3, hidden_gem_collector: 2 } },
        { id: 'tq-q4-c', label: 'Poor fabric quality', emoji: '✂️', weights: { quiet_luxury_collector: 2, designer_score_seeker: 2 } },
        { id: 'tq-q4-d', label: 'Looking too new', emoji: '🏷️', weights: { soft_vintage_curator: 3, downtown_treasure_hunter: 2 } },
        { id: 'tq-q4-e', label: 'Generic basics', emoji: '😐', weights: { eclectic_archivist: 3, street_romantic: 2 } },
        { id: 'tq-q4-f', label: 'Trend chasing', emoji: '📉', weights: { archive_hunter: 2, hidden_gem_collector: 2 } },
      ],
    },
    {
      id: 'tq-q5',
      text: 'What kind of compliment do you actually want?',
      options: [
        { id: 'tq-q5-a', label: '"Where did you find that?"', emoji: '🗺️', weights: { hidden_gem_collector: 3, downtown_treasure_hunter: 2 } },
        { id: 'tq-q5-b', label: '"You always have the best pieces."', emoji: '✦', weights: { archive_hunter: 3, quiet_luxury_collector: 1 } },
        { id: 'tq-q5-c', label: '"You look expensive."', emoji: '💰', weights: { quiet_luxury_collector: 3, designer_score_seeker: 1 } },
        { id: 'tq-q5-d', label: '"Nobody dresses like you."', emoji: '⚡', weights: { eclectic_archivist: 3, street_romantic: 2 } },
        { id: 'tq-q5-e', label: '"That piece is incredible."', emoji: '💎', weights: { designer_score_seeker: 3, archive_hunter: 1 } },
        { id: 'tq-q5-f', label: '"You always notice things others miss."', emoji: '🔍', weights: { hidden_gem_collector: 3, soft_vintage_curator: 2 } },
      ],
    },
    {
      id: 'tq-q6',
      text: 'What kind of piece feels impossible to leave behind?',
      options: [
        { id: 'tq-q6-a', label: 'Vintage leather jacket', emoji: '🧥', weights: { street_romantic: 3, archive_hunter: 2 } },
        { id: 'tq-q6-b', label: 'Perfectly worn-in denim', emoji: '👖', weights: { soft_vintage_curator: 3, downtown_treasure_hunter: 1 } },
        { id: 'tq-q6-c', label: 'Designer archive piece', emoji: '🪙', weights: { designer_score_seeker: 3, archive_hunter: 2 } },
        { id: 'tq-q6-d', label: 'Silk blouse or classic trench', emoji: '🤍', weights: { quiet_luxury_collector: 3, soft_vintage_curator: 1 } },
        { id: 'tq-q6-e', label: 'Strange graphic or statement piece', emoji: '⚡', weights: { eclectic_archivist: 3, street_romantic: 1 } },
        { id: 'tq-q6-f', label: 'Handmade or one-of-a-kind item', emoji: '🪡', weights: { hidden_gem_collector: 3, soft_vintage_curator: 2 } },
      ],
    },
  ],
  results: [
    {
      id: 'archive_hunter',
      label: 'Archive Hunter',
      tagline: 'You dress like the best pieces already existed before trends caught up.',
      description:
        'Your eye goes straight to the things other people walked past. You\'re not shopping — you\'re excavating. Every piece in your wardrobe feels like it was found, not bought, and that\'s the whole point. The archive isn\'t a reference for you. It\'s your native language.',
      identityLines: [
        '"Where did you get that?" is your most common compliment.',
        'You understand value that has nothing to do with price.',
        'Your wardrobe feels like a collection, not a closet.',
      ],
      outfitDirections: [
        'TOP — Structured vintage blazer in wool or tweed, slightly oversized',
        'BOTTOM — Straight-leg or wide-leg denim from the 80s or 90s',
        'SHOES — Worn-in leather loafers or classic Chelsea boots',
        'ACCESSORY — Silk scarf or archive-logo crossbody worn low',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #2A2018 0%, #1A140E 100%)', tags: ['vintage blazer'], query: ['cat_tops', 'cond_vintage'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #1A1E2A 0%, #10141E 100%)', tags: ['archive denim'], query: ['cat_bottoms', 'cond_vintage'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1E1810 0%, #140E08 100%)', tags: ['leather boots'], query: ['cat_footwear', 'cond_vintage'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #221C12 0%, #18120A 100%)', tags: ['silk scarf'], query: ['cat_accessories', 'cond_vintage'] },
      ],
      whyMyNextFit: 'My Next Thrift surfaces rare vintage and archive pieces across 80+ curated stores — so every recommendation feels like a real find.',
      accentColor: '#C4965A',
    },
    {
      id: 'street_romantic',
      label: 'Street Romantic',
      tagline: 'You like softness with edge — pieces that feel emotional but sharp.',
      description:
        'You pull off combinations most people wouldn\'t dare try. Feminine pieces with edge, vintage with a soft touch — your aesthetic lives in the tension between the two. People always ask where you got something because they\'ve never seen it worn that way.',
      identityLines: [
        'You wear contradictions like they were made for you.',
        'Soft and sharp. Tender and tough.',
        'Your fits follow a feeling, not a formula.',
      ],
      outfitDirections: [
        'TOP — Worn vintage leather jacket, slightly cropped',
        'BOTTOM — Flowy midi skirt or wide-leg trousers in a soft fabric',
        'SHOES — Vintage sneakers or pointed ankle boots',
        'ACCESSORY — Layered vintage chain necklaces or a small shoulder bag',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #1A1020 0%, #100818 100%)', tags: ['leather jacket'], query: ['cat_tops', 'cond_vintage'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #1E1428 0%, #140E1E 100%)', tags: ['flowy skirt'], query: ['cat_bottoms', 'cond_secondhand'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1C1020 0%, #120A16 100%)', tags: ['vintage sneakers'], query: ['cat_footwear', 'cond_vintage'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #201428 0%, #160E1C 100%)', tags: ['layered chains'], query: ['cat_accessories', 'cond_vintage'] },
      ],
      whyMyNextFit: 'My Next Thrift gets your mix-and-match aesthetic and surfaces vintage pieces that play well with what you already own.',
      accentColor: '#9B7EC8',
    },
    {
      id: 'quiet_luxury_collector',
      label: 'Quiet Luxury Collector',
      tagline: 'You notice fabric, silhouette, and restraint before logos.',
      description:
        'There\'s a quiet confidence to how you dress that most people can\'t quite name. You understand that real luxury is about how something feels, not what\'s on the tag. You\'ve found designer pieces for $18 at the back of a rack, and you wear them better than the original buyer did.',
      identityLines: [
        'Understated is your power move.',
        'Real quality needs no announcement.',
        'You find things that outperform their price for life.',
      ],
      outfitDirections: [
        'TOP — Cashmere crewneck or silk blouse in a soft neutral',
        'BOTTOM — Tailored wide-leg trousers or straight-cut wool pants',
        'SHOES — Leather loafers or classic pumps in cognac or black',
        'ACCESSORY — Simple leather belt or structured bag with clean hardware',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #1E1A14 0%, #141008 100%)', tags: ['cashmere / silk'], query: ['cat_tops', 'cond_secondhand'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #1A1810 0%, #120E08 100%)', tags: ['tailored trousers'], query: ['cat_bottoms', 'cond_secondhand'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1C1A10 0%, #14100A 100%)', tags: ['leather loafers'], query: ['cat_footwear', 'cond_secondhand'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #201E14 0%, #18140C 100%)', tags: ['structured bag'], query: ['cat_accessories', 'cond_secondhand'] },
      ],
      whyMyNextFit: 'My Next Thrift finds the quiet luxury pieces you actually want — designer-quality fabric, no logo noise.',
      accentColor: '#D4C5A0',
    },
    {
      id: 'downtown_treasure_hunter',
      label: 'Downtown Treasure Hunter',
      tagline: 'You dress like every piece has a better story than the room you\'re in.',
      description:
        'You\'ve always had an instinct for places others overlook. The back-of-the-rack find. The estate sale blazer. The thrift store gem that turns heads at dinner. Your wardrobe is a map of everywhere you\'ve looked — and found something real.',
      identityLines: [
        'Every piece in your wardrobe has a story.',
        'You thrift like you know exactly what you\'re looking for.',
        'Your eye finds things that take others years to notice.',
      ],
      outfitDirections: [
        'TOP — Vintage structured coat or heavy wool overshirt',
        'BOTTOM — Slim or tapered vintage denim or corduroy',
        'SHOES — Worn-in leather boots or heritage sneakers',
        'ACCESSORY — Vintage watch or a beat-up canvas bag with character',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #1A1612 0%, #100E08 100%)', tags: ['vintage coat'], query: ['cat_tops', 'cond_vintage'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #141820 0%, #0E1018 100%)', tags: ['tapered denim'], query: ['cat_bottoms', 'cond_vintage'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1A1410 0%, #120E08 100%)', tags: ['heritage boots'], query: ['cat_footwear', 'cond_vintage'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #1C1810 0%, #14100A 100%)', tags: ['vintage watch'], query: ['cat_accessories', 'cond_vintage'] },
      ],
      whyMyNextFit: 'My Next Thrift is built for the treasure hunter — real vintage from 80+ curated stores, scored and ranked so the best finds surface first.',
      accentColor: '#8B7355',
    },
    {
      id: 'hidden_gem_collector',
      label: 'Hidden Gem Collector',
      tagline: 'You find beauty in pieces most people overlook.',
      description:
        'You have a rare kind of patience. You\'re not looking for labels — you\'re looking for something that just feels right. And when you find it, you know immediately. Your eye is trained on what most people walk past, which is exactly why your wardrobe looks like nobody else\'s.',
      identityLines: [
        '"You always notice things others miss."',
        'You\'re not chasing brands. You\'re chasing feeling.',
        'Your best finds cost less than dinner.',
      ],
      outfitDirections: [
        'TOP — An overlooked vintage piece — interesting texture, odd detail, perfectly cut',
        'BOTTOM — Simple wide-leg or straight-leg pants that feel almost expensive',
        'SHOES — Understated vintage boots or simple leather mules',
        'ACCESSORY — One strange or beautiful piece that makes the whole look',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #1A1820 0%, #10101A 100%)', tags: ['textured top'], query: ['cat_tops', 'cond_vintage'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #181820 0%, #101018 100%)', tags: ['wide-leg'], query: ['cat_bottoms', 'cond_secondhand'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1A1818 0%, #121010 100%)', tags: ['simple boots'], query: ['cat_footwear', 'cond_vintage'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #1C1A20 0%, #141218 100%)', tags: ['statement piece'], query: ['cat_accessories', 'cond_vintage'] },
      ],
      whyMyNextFit: 'My Next Thrift\'s gem score surfaces rare, underrated pieces with high visual quality — the finds most people scroll past.',
      accentColor: '#7B9E87',
    },
    {
      id: 'designer_score_seeker',
      label: 'Designer Score Seeker',
      tagline: 'You love the thrill of finding luxury where nobody else was looking.',
      description:
        'You understand the game. The designer blazer at a fraction of retail. The bag that goes for $800 found for $40. You\'re not buying secondhand because you have to — you\'re buying secondhand because you\'ve cracked the code. The thrill of the find is part of the point.',
      identityLines: [
        'You\'ve found $800 bags for $40.',
        'You know what something is worth before you see the price tag.',
        'The hunt is half the reason.',
      ],
      outfitDirections: [
        'TOP — Designer or luxury-brand vintage blazer, knit, or shirt',
        'BOTTOM — Tailored designer trousers or high-quality vintage denim',
        'SHOES — Heritage designer boots or loafers built to last decades',
        'ACCESSORY — A designer bag or belt worn like it\'s the most natural thing',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #1E1A10 0%, #141008 100%)', tags: ['designer top'], query: ['cat_tops', 'cond_vintage'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #1A1810 0%, #12100A 100%)', tags: ['tailored'], query: ['cat_bottoms', 'cond_secondhand'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1C1A12 0%, #141008 100%)', tags: ['heritage footwear'], query: ['cat_footwear', 'cond_vintage'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #201C12 0%, #16120C 100%)', tags: ['designer bag'], query: ['cat_accessories', 'cond_secondhand'] },
      ],
      whyMyNextFit: 'My Next Thrift scans 80+ vintage and secondhand stores for designer pieces — ranked by rarity so the real finds surface first.',
      accentColor: '#D4A830',
    },
    {
      id: 'soft_vintage_curator',
      label: 'Soft Vintage Curator',
      tagline: 'You collect pieces that feel nostalgic, personal, and emotionally textured.',
      description:
        'You\'re drawn to things that feel lived-in, loved, and quietly beautiful. The faded floral. The soft knit washed a hundred times. The blouse that looks like it has a history. Your wardrobe has a warmth to it that people feel before they can describe it.',
      identityLines: [
        'You dress for how a piece makes you feel, not how it looks on a rack.',
        'Your favorite items feel like they\'ve always been yours.',
        'Softness, texture, and history — that\'s the whole brief.',
      ],
      outfitDirections: [
        'TOP — Worn floral blouse or soft vintage knit in a faded, warm tone',
        'BOTTOM — High-waisted vintage jeans or a flowy linen skirt',
        'SHOES — Soft leather sandals or well-worn canvas shoes',
        'ACCESSORY — Delicate vintage jewelry — a locket, pearl earrings, or thin layered chains',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #201614 0%, #160E0C 100%)', tags: ['floral / knit'], query: ['cat_tops', 'cond_vintage'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #1A1C14 0%, #10120E 100%)', tags: ['linen / denim'], query: ['cat_bottoms', 'cond_vintage'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1C1814 0%, #14100C 100%)', tags: ['canvas / sandals'], query: ['cat_footwear', 'cond_vintage'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #201A14 0%, #16100E 100%)', tags: ['vintage jewelry'], query: ['cat_accessories', 'cond_vintage'] },
      ],
      whyMyNextFit: 'My Next Thrift finds the soft, emotionally-textured pieces you\'re drawn to — warm, worn-in, and unlike anything in a fast fashion store.',
      accentColor: '#C4907A',
    },
    {
      id: 'eclectic_archivist',
      label: 'Eclectic Archivist',
      tagline: 'You make unrelated pieces feel like they belong together.',
      description:
        'Your wardrobe shouldn\'t work on paper, but it does. The 70s blazer with the 90s graphic tee. The silk slip under a heavyweight coat. You\'ve developed an internal logic that most people can\'t decode — and that\'s entirely the point. You dress for yourself, and it shows.',
      identityLines: [
        'Your outfits are impossible to replicate.',
        'You have an internal logic nobody else can decode.',
        '"Hard to categorize" is your favorite compliment.',
      ],
      outfitDirections: [
        'TOP — Oversized vintage graphic tee or band shirt, worn with confidence',
        'BOTTOM — Vintage wide-leg or baggy jeans, slightly worn',
        'SHOES — Chunky vintage boots or completely unexpected sneakers',
        'ACCESSORY — One bold, strange piece that anchors the whole look',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #141420 0%, #0C0C18 100%)', tags: ['graphic tee'], query: ['cat_tops', 'cond_vintage'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #12141E 0%, #0C0E16 100%)', tags: ['wide-leg denim'], query: ['cat_bottoms', 'cond_vintage'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #161420 0%, #0E0C18 100%)', tags: ['chunky boots'], query: ['cat_footwear', 'cond_vintage'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #181420 0%, #100C18 100%)', tags: ['bold accessory'], query: ['cat_accessories', 'cond_vintage'] },
      ],
      whyMyNextFit: 'My Next Thrift feeds your eclectic instinct — rare vintage from 80+ curated stores with enough range to keep your combinations surprising.',
      accentColor: '#7B8FD0',
    },
  ],
};
