import { QuizConfig, CuratedImage } from '@/types/quiz';

// Reuse the same 8 archetypes and visualCards/curatedImages from style-quiz
// but with fresh question angles targeting vintage aesthetic search traffic.
// Results reference the same IDs so scoring maps correctly.

export const vintageAestheticQuiz: QuizConfig = {
  id: 'vintage-aesthetic',
  slug: 'vintage-aesthetic',
  hook: "Vintage isn't a style. It's a point of view.",
  hookSubtext: '6 questions to find the vintage eye you already have.',
  ctaLabel: 'Find my aesthetic →',
  questions: [
    {
      id: 'va-q1',
      text: 'What era do you gravitate toward without thinking?',
      subtext: 'The one that already feels like home.',
      options: [
        { id: 'va-q1-a', label: '70s — warm earth tones, wide collars, worn leather', emoji: '✿', weights: { soft_vintage_curator: 3, street_romantic: 1 } },
        { id: 'va-q1-b', label: '80s — structured shoulders, bold cuts, power silhouettes', emoji: '⬛', weights: { archive_hunter: 3, designer_score_seeker: 1 } },
        { id: 'va-q1-c', label: '90s — minimalism, slip dresses, understated cool', emoji: '◻️', weights: { quiet_luxury_collector: 3, hidden_gem_collector: 1 } },
        { id: 'va-q1-d', label: 'Y2K — low-rise, metallic, experimental mash-ups', emoji: '💿', weights: { eclectic_archivist: 3, designer_score_seeker: 1 } },
        { id: 'va-q1-e', label: 'Timeless — pre-70s heritage pieces that transcend decades', emoji: '⌛', weights: { downtown_treasure_hunter: 3, archive_hunter: 1 } },
        { id: 'va-q1-f', label: 'Mix — I pull from every era, never just one', emoji: '🌀', weights: { street_romantic: 3, eclectic_archivist: 1 } },
      ],
    },
    {
      id: 'va-q2',
      text: 'What hits you first when a vintage piece catches your eye?',
      options: [
        { id: 'va-q2-a', label: 'The fabric — I can feel quality through a photo', emoji: '🪡', weights: { quiet_luxury_collector: 3, soft_vintage_curator: 1 } },
        { id: 'va-q2-b', label: 'The silhouette — I see the shape before anything else', emoji: '🖤', weights: { archive_hunter: 3, downtown_treasure_hunter: 1 } },
        { id: 'va-q2-c', label: 'The label — I know what I\'m looking at instantly', emoji: '🏷️', weights: { designer_score_seeker: 3, quiet_luxury_collector: 1 } },
        { id: 'va-q2-d', label: 'The story — I want to know where it\'s been', emoji: '📖', weights: { downtown_treasure_hunter: 3, soft_vintage_curator: 1 } },
        { id: 'va-q2-e', label: 'The weirdness — if it\'s strange I\'m already invested', emoji: '⚡', weights: { eclectic_archivist: 3, street_romantic: 1 } },
        { id: 'va-q2-f', label: 'The rarity — I can tell when nobody else will have it', emoji: '💎', weights: { hidden_gem_collector: 3, designer_score_seeker: 1 } },
      ],
    },
    {
      id: 'va-q3',
      text: 'What color world do you live in?',
      options: [
        { id: 'va-q3-a', label: 'Earthy — browns, rust, olive, ochre, terracotta', emoji: '🟤', weights: { soft_vintage_curator: 3, downtown_treasure_hunter: 1 } },
        { id: 'va-q3-b', label: 'Dark — black, charcoal, deep navy, midnight', emoji: '⬛', weights: { street_romantic: 3, eclectic_archivist: 1 } },
        { id: 'va-q3-c', label: 'Neutral — cream, beige, camel, ivory, taupe', emoji: '🤍', weights: { quiet_luxury_collector: 3, hidden_gem_collector: 1 } },
        { id: 'va-q3-d', label: 'Bold — saturated jewel tones, unexpected pops', emoji: '🟣', weights: { eclectic_archivist: 3, designer_score_seeker: 1 } },
        { id: 'va-q3-e', label: 'Washed — faded, sun-bleached, lived-in softness', emoji: '🌫️', weights: { hidden_gem_collector: 3, soft_vintage_curator: 1 } },
        { id: 'va-q3-f', label: 'Heritage — tweed browns, leather blacks, denim blues', emoji: '🧵', weights: { archive_hunter: 3, downtown_treasure_hunter: 1 } },
      ],
    },
    {
      id: 'va-q4',
      text: 'What instantly kills a vintage piece for you?',
      options: [
        { id: 'va-q4-a', label: 'Visible logos — ruins the mystery', emoji: '🚫', weights: { quiet_luxury_collector: 3, hidden_gem_collector: 1 } },
        { id: 'va-q4-b', label: 'Feels mass-produced — no soul, no history', emoji: '🏭', weights: { archive_hunter: 3, downtown_treasure_hunter: 1 } },
        { id: 'va-q4-c', label: 'Too trendy — I want pieces that outlast seasons', emoji: '📉', weights: { downtown_treasure_hunter: 3, soft_vintage_curator: 1 } },
        { id: 'va-q4-d', label: 'Looks brand new — I need some wear, some life', emoji: '✨', weights: { soft_vintage_curator: 3, street_romantic: 1 } },
        { id: 'va-q4-e', label: 'Too safe — if it doesn\'t surprise me I move on', emoji: '😐', weights: { eclectic_archivist: 3, street_romantic: 1 } },
        { id: 'va-q4-f', label: 'Bad fabric — you can\'t fake material', emoji: '✂️', weights: { designer_score_seeker: 3, quiet_luxury_collector: 1 } },
      ],
    },
    {
      id: 'va-q5',
      text: 'What compliment makes your vintage heart race?',
      options: [
        { id: 'va-q5-a', label: '"Is that actually vintage? It looks incredible."', emoji: '🗝️', weights: { archive_hunter: 3, downtown_treasure_hunter: 1 } },
        { id: 'va-q5-b', label: '"You look expensive — in the quiet way."', emoji: '💰', weights: { quiet_luxury_collector: 3, designer_score_seeker: 1 } },
        { id: 'va-q5-c', label: '"I\'ve never seen anything like that. Where did you find it?"', emoji: '💎', weights: { hidden_gem_collector: 3, eclectic_archivist: 1 } },
        { id: 'va-q5-d', label: '"You put things together in a way nobody else would."', emoji: '⚡', weights: { eclectic_archivist: 3, street_romantic: 1 } },
        { id: 'va-q5-e', label: '"That piece has such a feeling to it."', emoji: '🌙', weights: { street_romantic: 3, soft_vintage_curator: 1 } },
        { id: 'va-q5-f', label: '"Is that [designer]? How did you score that?"', emoji: '🪙', weights: { designer_score_seeker: 3, quiet_luxury_collector: 1 } },
        { id: 'va-q5-g', label: '"You always find things with real history."', emoji: '📦', weights: { downtown_treasure_hunter: 3, archive_hunter: 1 } },
        { id: 'va-q5-h', label: '"That looks like it was made for you."', emoji: '✦', weights: { soft_vintage_curator: 3, hidden_gem_collector: 1 } },
      ],
    },
    {
      id: 'va-q6',
      text: 'What vintage piece could you never leave behind?',
      options: [
        { id: 'va-q6-a', label: 'Perfectly worn leather jacket with real patina', emoji: '🧥', weights: { street_romantic: 3, archive_hunter: 1 } },
        { id: 'va-q6-b', label: 'Designer blazer from an era when things were built to last', emoji: '🤍', weights: { quiet_luxury_collector: 3, designer_score_seeker: 1 } },
        { id: 'va-q6-c', label: 'Strange statement piece that makes no sense on the hanger', emoji: '🌀', weights: { eclectic_archivist: 3, street_romantic: 1 } },
        { id: 'va-q6-d', label: 'Vintage denim worn soft over decades — no reproduction', emoji: '👖', weights: { soft_vintage_curator: 3, downtown_treasure_hunter: 1 } },
        { id: 'va-q6-e', label: 'Archive coat or jacket with construction you don\'t see anymore', emoji: '📦', weights: { archive_hunter: 3, downtown_treasure_hunter: 1 } },
        { id: 'va-q6-f', label: 'Luxury bag or shoe at a price that shouldn\'t exist', emoji: '🪙', weights: { designer_score_seeker: 3, quiet_luxury_collector: 1 } },
        { id: 'va-q6-g', label: 'A piece so obscure nobody can identify it — including me', emoji: '🔮', weights: { hidden_gem_collector: 3, eclectic_archivist: 1 } },
        { id: 'va-q6-h', label: 'Workwear piece with decades of honest wear built in', emoji: '🔧', weights: { downtown_treasure_hunter: 3, archive_hunter: 1 } },
      ],
    },
  ],
  results: [
    {
      id: 'archive_hunter',
      label: 'Archive Hunter',
      tagline: 'You dress like the best pieces already existed before trends caught up.',
      description: 'Your eye goes straight to the things other people walked past. You\'re not shopping — you\'re excavating. Every piece in your wardrobe feels like it was found, not bought, and that\'s the whole point. The archive isn\'t a reference for you. It\'s your native language.',
      identityLines: [
        '"Where did you get that?" is your most common compliment.',
        'You understand value that has nothing to do with price.',
        'Your wardrobe feels like a collection, not a closet.',
      ],
      outfitDirections: [
        'TOP — Structured vintage blazer in wool or tweed, slightly oversized',
        'BOTTOM — Straight-leg or wide-leg denim from the 80s or 90s',
        'SHOES — Worn-in leather loafers or classic Chelsea boots',
        'ACCESSORY — Silk scarf or archive-logo crossbody worn low',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #2A2018 0%, #1A140E 100%)', tags: ['vintage blazer'], query: ['cat_tops', 'style_classic', 'cond_vintage'], titleKeywords: ['blazer', 'jacket', 'coat'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #1A1E2A 0%, #10141E 100%)', tags: ['archive denim'], query: ['cat_bottoms', 'style_classic', 'cond_vintage'], titleKeywords: ['denim', 'jean', 'trouser', 'cord'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1E1810 0%, #140E08 100%)', tags: ['leather boots'], query: ['cat_footwear', 'style_classic', 'cond_vintage'], titleKeywords: ['boot', 'loafer', 'oxford'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #221C12 0%, #18120A 100%)', tags: ['silk scarf'], query: ['cat_accessories', 'style_classic', 'cond_vintage'], titleKeywords: ['scarf', 'crossbody', 'belt', 'wallet'] },
      ],
      whyMyNextFit: 'A feed built around the eye that already knows what it\'s looking for. The pieces that reach you feel excavated, not recommended.',
      accentColor: '#C4965A',
    },
    {
      id: 'street_romantic',
      label: 'Street Romantic',
      tagline: 'You like softness with edge — pieces that feel emotional but sharp.',
      description: 'You pull off combinations most people wouldn\'t dare try. Feminine pieces with edge, vintage with a soft touch — your aesthetic lives in the tension between the two. People always ask where you got something because they\'ve never seen it worn that way.',
      identityLines: [
        'You wear contradictions like they were made for you.',
        'Soft and sharp. Tender and tough.',
        'Your fits follow a feeling, not a formula.',
      ],
      outfitDirections: [
        'TOP — Worn vintage leather jacket, slightly cropped',
        'BOTTOM — Flowy midi skirt or wide-leg trousers in a soft fabric',
        'SHOES — Vintage sneakers or pointed ankle boots',
        'ACCESSORY — Layered vintage chain necklaces or a small shoulder bag',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #1A1020 0%, #100818 100%)', tags: ['leather jacket'], query: ['cat_tops', 'style_bohemian', 'cond_vintage'], titleKeywords: ['leather', 'jacket', 'blouse', 'floral'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #1E1428 0%, #140E1E 100%)', tags: ['flowy skirt'], query: ['cat_bottoms', 'style_bohemian', 'cond_vintage'], titleKeywords: ['skirt', 'midi', 'linen', 'flowy'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1C1020 0%, #120A16 100%)', tags: ['ankle boots'], query: ['cat_footwear', 'style_bohemian', 'cond_vintage'], titleKeywords: ['boot', 'ankle', 'sneaker', 'chelsea'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #201428 0%, #160E1C 100%)', tags: ['layered chains'], query: ['cat_accessories', 'style_bohemian', 'cond_vintage'], titleKeywords: ['necklace', 'chain', 'earring', 'ring'] },
      ],
      whyMyNextFit: 'Pieces with enough edge and softness to hold the tension your eye is always after. The find that works in a context it wasn\'t designed for.',
      accentColor: '#9B7EC8',
    },
    {
      id: 'quiet_luxury_collector',
      label: 'Quiet Luxury Collector',
      tagline: 'You notice fabric, silhouette, and restraint before logos.',
      description: 'There\'s a quiet confidence to how you dress that most people can\'t quite name. You understand that real luxury is about how something feels, not what\'s on the tag. You\'ve found designer pieces for $18 at the back of a rack, and you wear them better than the original buyer did.',
      identityLines: [
        'Understated is your power move.',
        'Real quality needs no announcement.',
        'You find things that outperform their price for life.',
      ],
      outfitDirections: [
        'TOP — Cashmere crewneck or silk blouse in a soft neutral',
        'BOTTOM — Tailored wide-leg trousers or straight-cut wool pants',
        'SHOES — Leather loafers or classic pumps in cognac or black',
        'ACCESSORY — Simple leather belt or structured bag with clean hardware',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #1E1A14 0%, #141008 100%)', tags: ['cashmere / silk'], query: ['cat_tops', 'style_luxury', 'cond_secondhand'], titleKeywords: ['cashmere', 'silk', 'blouse', 'knit', 'sweater'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #1A1810 0%, #120E08 100%)', tags: ['tailored trousers'], query: ['cat_bottoms', 'style_luxury', 'cond_secondhand'], titleKeywords: ['trouser', 'wool', 'crepe', 'wide-leg'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1C1A10 0%, #14100A 100%)', tags: ['leather loafers'], query: ['cat_footwear', 'style_luxury', 'cond_secondhand'], titleKeywords: ['loafer', 'pump', 'mule', 'heel'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #201E14 0%, #18140C 100%)', tags: ['structured bag'], query: ['cat_accessories', 'style_luxury', 'cond_secondhand'], titleKeywords: ['bag', 'tote', 'clutch', 'purse'] },
      ],
      whyMyNextFit: 'The pieces that reach you earned their place. Designer-quality fabric, no logo noise — found before the obvious crowd gets there.',
      accentColor: '#D4C5A0',
    },
    {
      id: 'downtown_treasure_hunter',
      label: 'Workwear Classicist',
      tagline: 'You dress in pieces built to last — utilitarian heritage, worn naturally.',
      description: 'You\'ve always had an instinct for places others overlook. The back-of-the-rack find. The estate sale blazer. The thrift store gem that turns heads at dinner. Your wardrobe is a map of everywhere you\'ve looked — and found something real.',
      identityLines: [
        'Chore coats. Selvedge denim. Canvas that ages correctly.',
        'Your wardrobe looks like it was assembled over decades, not seasons.',
        'You know the difference between workwear that works and workwear that performs.',
      ],
      outfitDirections: [
        'TOP — Vintage structured coat or heavy wool overshirt',
        'BOTTOM — Slim or tapered vintage denim or corduroy',
        'SHOES — Worn-in leather boots or heritage sneakers',
        'ACCESSORY — Vintage watch or a beat-up canvas bag with character',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #1A1612 0%, #100E08 100%)', tags: ['vintage coat'], query: ['cat_tops', 'style_workwear', 'cond_vintage'], titleKeywords: ['coat', 'jacket', 'blazer', 'overshirt', 'chore'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #141820 0%, #0E1018 100%)', tags: ['tapered denim'], query: ['cat_bottoms', 'style_workwear', 'cond_vintage'], titleKeywords: ['denim', 'jean', 'corduroy', 'chino'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1A1410 0%, #120E08 100%)', tags: ['heritage boots'], query: ['cat_footwear', 'style_workwear', 'cond_vintage'], titleKeywords: ['boot', 'oxford', 'derby'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #1C1810 0%, #14100A 100%)', tags: ['vintage watch'], query: ['cat_accessories', 'style_workwear', 'cond_vintage'], titleKeywords: ['watch', 'canvas', 'belt', 'wallet'] },
      ],
      whyMyNextFit: 'A feed that keeps pace with your instinct — the back-of-the-rack gem, the estate sale score, the thing that makes people stop and ask.',
      accentColor: '#8B7355',
    },
    {
      id: 'hidden_gem_collector',
      label: 'Understated Vintage',
      tagline: 'You dress in things people can\'t quite place — but always look at twice.',
      description: 'You have a rare kind of patience. You\'re not looking for labels — you\'re looking for something that just feels right. And when you find it, you know immediately. Your eye is trained on what most people walk past, which is exactly why your wardrobe looks like nobody else\'s.',
      identityLines: [
        'Your best pieces have no visible label and no explanation needed.',
        'Texture before color. Drape before cut. Fabric before everything.',
        'The fit you get the most compliments on cost less than dinner.',
      ],
      outfitDirections: [
        'TOP — An overlooked vintage piece — interesting texture, odd detail, perfectly cut',
        'BOTTOM — Simple wide-leg or straight-leg pants that feel almost expensive',
        'SHOES — Understated vintage boots or simple leather mules',
        'ACCESSORY — One strange or beautiful piece that makes the whole look',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #1A1820 0%, #10101A 100%)', tags: ['textured top'], query: ['cat_tops', 'style_minimalist', 'cond_vintage'], titleKeywords: ['knit', 'blouse', 'sweater', 'cardigan', 'linen'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #181820 0%, #101018 100%)', tags: ['wide-leg'], query: ['cat_bottoms', 'style_minimalist', 'cond_vintage'], titleKeywords: ['trouser', 'wide', 'linen', 'corduroy'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1A1818 0%, #121010 100%)', tags: ['simple boots'], query: ['cat_footwear', 'style_minimalist', 'cond_vintage'], titleKeywords: ['boot', 'mule', 'loafer'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #1C1A20 0%, #141218 100%)', tags: ['statement piece'], query: ['cat_accessories', 'style_minimalist', 'cond_vintage'], titleKeywords: ['necklace', 'ring', 'earring', 'brooch'] },
      ],
      whyMyNextFit: 'Pieces most people walk right past. Your eye catches what others miss — the feed reflects that, not the other way around.',
      accentColor: '#7B9E87',
    },
    {
      id: 'designer_score_seeker',
      label: 'Designer Score Seeker',
      tagline: 'You love the thrill of finding luxury where nobody else was looking.',
      description: 'You understand the game. The designer blazer at a fraction of retail. The bag that goes for $800 found for $40. You\'re not buying secondhand because you have to — you\'re buying secondhand because you\'ve cracked the code. The thrill of the find is part of the point.',
      identityLines: [
        'You\'ve found $800 bags for $40.',
        'You know what something is worth before you see the price tag.',
        'The hunt is half the reason.',
      ],
      outfitDirections: [
        'TOP — Designer or luxury-brand vintage blazer, knit, or shirt',
        'BOTTOM — Tailored designer trousers or high-quality vintage denim',
        'SHOES — Heritage designer boots or loafers built to last decades',
        'ACCESSORY — A designer bag or belt worn like it\'s the most natural thing',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #1E1A10 0%, #141008 100%)', tags: ['designer top'], query: ['cat_tops', 'style_luxury', 'cond_vintage'], titleKeywords: ['blazer', 'jacket', 'coat', 'cashmere', 'silk'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #1A1810 0%, #12100A 100%)', tags: ['tailored'], query: ['cat_bottoms', 'style_luxury', 'cond_vintage'], titleKeywords: ['trouser', 'wide-leg', 'wool', 'crepe'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1C1A12 0%, #141008 100%)', tags: ['heritage footwear'], query: ['cat_footwear', 'style_luxury', 'cond_vintage'], titleKeywords: ['boot', 'loafer', 'pump', 'heel'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #201C12 0%, #16120C 100%)', tags: ['designer bag'], query: ['cat_accessories', 'style_luxury', 'cond_vintage'], titleKeywords: ['bag', 'clutch', 'purse', 'tote'] },
      ],
      whyMyNextFit: 'The thrill is the find. Rare designer pieces at prices that shouldn\'t exist — the kind your eye spots before anyone else does.',
      accentColor: '#D4A830',
    },
    {
      id: 'soft_vintage_curator',
      label: 'Soft Vintage',
      tagline: 'You buy things that look like they were already worn by someone interesting.',
      description: 'You\'re drawn to things that feel lived-in, loved, and quietly beautiful. The faded floral. The soft knit washed a hundred times. The blouse that looks like it has a history. Your wardrobe has a warmth to it that people feel before they can describe it.',
      identityLines: [
        'Faded florals. Worn linen. Earrings that belonged to someone\'s grandmother.',
        'Your closet looks like a film still from 1974.',
        'Softness is a point of view, not a style category.',
      ],
      outfitDirections: [
        'TOP — Worn floral blouse or soft vintage knit in a faded, warm tone',
        'BOTTOM — High-waisted vintage jeans or a flowy linen skirt',
        'SHOES — Soft leather sandals or well-worn canvas shoes',
        'ACCESSORY — Delicate vintage jewelry — a locket, pearl earrings, or thin layered chains',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #201614 0%, #160E0C 100%)', tags: ['floral / knit'], query: ['cat_tops', 'style_bohemian', 'cond_vintage'], titleKeywords: ['blouse', 'knit', 'floral', 'sweater', 'cardigan'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #1A1C14 0%, #10120E 100%)', tags: ['linen / denim'], query: ['cat_bottoms', 'style_bohemian', 'cond_vintage'], titleKeywords: ['linen', 'denim', 'jean', 'skirt', 'midi'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #1C1814 0%, #14100C 100%)', tags: ['canvas / sandals'], query: ['cat_footwear', 'style_bohemian', 'cond_vintage'], titleKeywords: ['sandal', 'canvas', 'mule', 'clog'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #201A14 0%, #16100E 100%)', tags: ['vintage jewelry'], query: ['cat_accessories', 'style_bohemian', 'cond_vintage'], titleKeywords: ['necklace', 'earring', 'locket', 'pearl', 'chain'] },
      ],
      whyMyNextFit: 'The worn-in blouse that feels like it was always yours. The faded knit you can\'t explain. Pieces with warmth that shows before you can describe it.',
      accentColor: '#C4907A',
    },
    {
      id: 'eclectic_archivist',
      label: 'Eclectic Archivist',
      tagline: 'You make unrelated pieces feel like they belong together.',
      description: 'Your wardrobe shouldn\'t work on paper, but it does. The 70s blazer with the 90s graphic tee. The silk slip under a heavyweight coat. You\'ve developed an internal logic that most people can\'t decode — and that\'s entirely the point. You dress for yourself, and it shows.',
      identityLines: [
        'Your outfits are impossible to replicate.',
        'You have an internal logic nobody else can decode.',
        '"Hard to categorize" is your favorite compliment.',
      ],
      outfitDirections: [
        'TOP — Oversized vintage graphic tee or band shirt, worn with confidence',
        'BOTTOM — Vintage wide-leg or baggy jeans, slightly worn',
        'SHOES — Chunky vintage boots or completely unexpected sneakers',
        'ACCESSORY — One bold, strange piece that anchors the whole look',
      ],
      visualCards: [
        { label: 'TOP', gradient: 'linear-gradient(145deg, #141420 0%, #0C0C18 100%)', tags: ['graphic tee'], query: ['cat_tops', 'style_streetwear', 'cond_vintage'], titleKeywords: ['graphic', 'band', 'print', 'jersey', 'tee'] },
        { label: 'BOTTOM', gradient: 'linear-gradient(145deg, #12141E 0%, #0C0E16 100%)', tags: ['wide-leg denim'], query: ['cat_bottoms', 'style_streetwear', 'cond_vintage'], titleKeywords: ['denim', 'jean', 'baggy', 'wide'] },
        { label: 'SHOES', gradient: 'linear-gradient(145deg, #161420 0%, #0E0C18 100%)', tags: ['chunky boots'], query: ['cat_footwear', 'style_streetwear', 'cond_vintage'], titleKeywords: ['boot', 'sneaker', 'platform', 'chunky'] },
        { label: 'ACCESSORY', gradient: 'linear-gradient(145deg, #181420 0%, #100C18 100%)', tags: ['bold accessory'], query: ['cat_accessories', 'style_streetwear', 'cond_vintage'], titleKeywords: ['necklace', 'ring', 'earring', 'pendant'] },
      ],
      whyMyNextFit: 'Pieces with enough character that your combinations keep surprising even you. The find from a different world that somehow completes the look.',
      accentColor: '#7B8FD0',
    },
  ],
} as QuizConfig;
